#!/usr/bin/env bash
#a Bash script that displays:
#The content of the current directory
#In a lst format
#Where only the part of the name after the first dash is displayed (refer to the example)
#Using for loop
#do not diplay hidden files

list-$(ls)
for i in $list; do
	echo "$i" | cut -d '-' -f2
done
